server:
  port: 8888
spring:
  profiles:
# enable file system backend
# see: https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#_file_system_backend
    active: native
  security:
    user:
      name: root
      password: s3cr3t
  # git backend config
  # cloud:
  #   config:
  #     server:
  #       git:
  #         uri: <git repo url>